name: Integration continue
on:
  push:
    branches:
      - main
    tags:
      - '**'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation de NodeJS / Cache / Deps
        uses: ./.github/actions/setup-node
      - name: Build
        run: npm run build -w backend
      - uses: actions/upload-artifact@v2
        with:
          name: backend-build
          path: backend/dist
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation de NodeJS / Cache / Deps
        uses: ./.github/actions/setup-node
        with:
          node-version: 18.x
          run_install: false
      - name: Build
        run: npm run build -w frontend
      - uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: frontend/dist
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation de NodeJS / Cache / Deps
        uses: ./.github/actions/setup-node
      - name: Test
        run: npm run test -w backend
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation de NodeJS / Cache / Deps
        uses: ./.github/actions/setup-node
      - name: Test
        run: npm run test -w frontend
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation de NodeJS / Cache / Deps
        uses: ./.github/actions/setup-node
      - name: Lint
        run: npm run lint -w backend
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation de NodeJS / Cache / Deps
        uses: ./.github/actions/setup-node
      - name: Lint
        run: npm run lint -w frontend

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-frontend, build-backend, test-frontend, test-backend, lint-frontend, lint-backend]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: zip -q -r dist.zip backend/dist frontend/dist
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist.zip
